### ISSUE TITLE
May I know what theme you use for the preview GIF

### ISSUE THREAD

**Issue by krehwell** [skanehira/christmas.vim#2]
not really an issue, but I like ur theme on this [preview](https://camo.githubusercontent.com/ba13dfaf9a53f193ad66531f6fe44d9e5f8d39e43c6e67b87dc75679a38a944b/68747470733a2f2f692e6779617a6f2e636f6d2f36613635363465393635363439393362313333383133636563636534393865332e676966)

may I know what colorscheme is that? and what colorscheme do you use for the lightline too

**Comment by skanehira** [comment]
I'm using [cocopon/iceberg.vim](https://github.com/cocopon/iceberg.vim) :)

**Comment by krehwell** [comment]
Iceberge seems to have syntax highlighting, may I know how do you make yours so its plain black and white?

**Comment by skanehira** [comment]
@krehwell I just use `:syntax clear` at buffer

https://github.com/skanehira/dotfiles/blob/15ce2cfc3a8000ebeccee11ac83d064dd7301634/vim/vimrc#L713-L721
